    const graph = data.graph ?? data.document;
    const vscode = typeof acquireVsCodeApi === 'function' ? acquireVsCodeApi() : undefined;
    const graphNodes = Array.isArray(graph?.nodes) ? graph.nodes : [];
    const nodes = new Map(graphNodes.map(node => [node.name, node]));
    const entryName = data.entryNodeName ?? '';
    const metadataEntry = graphNodes.find(node => (node.lines ?? []).some(line => line.kind === 'Metadata' && (line.text ?? '').trim() === '@entry'));
    const entry = entryName ? nodes.get(entryName) : metadataEntry;
    const initialCurrent = entry?.name ?? graphNodes[0]?.name ?? '';
    const previousState = vscode && typeof vscode.getState === 'function' ? vscode.getState() : undefined;
    let current = previousState?.current && nodes.has(previousState.current) ? previousState.current : initialCurrent;
    let path = Array.isArray(previousState?.path) ? previousState.path.filter(name => nodes.has(name)) : [];
    let focusedSource = undefined;
    if (!path.length || path[path.length - 1] !== current) { path = current ? [current] : []; }
    function clear(element) { while (element.firstChild) element.removeChild(element.firstChild); }
    function sourcePayload(source) { return source && source.sourcePath ? { sourcePath: source.sourcePath, line: Math.max(0, (source.line ?? 1) - 1), character: Math.max(0, (source.column ?? 1) - 1) } : undefined; }
    function editorSourcePayload(source) { return source && source.sourcePath ? { sourcePath: source.sourcePath, line: Math.max(0, (source.line ?? 0)), character: Math.max(0, (source.character ?? source.column ?? 0)) } : undefined; }
    function openSource(source) { const payload = editorSourcePayload(source); if (!payload || !vscode) return; vscode.postMessage({ type: 'openSource', source: payload }); }
    function normalizeSourcePath(value) { return String(value ?? '').replace(/\\/g, '/').toLowerCase(); }
    function sameSourcePath(left, right) { return !!left && !!right && normalizeSourcePath(left) === normalizeSourcePath(right); }
    function sourceMatches(candidate, target) { const payload = sourcePayload(candidate); return !!payload && !!target && sameSourcePath(payload.sourcePath, target.sourcePath) && payload.line === Math.max(0, (target.line ?? 0)); }
    function collectNodeSources(node) { const entries = []; if (node?.source) entries.push(node.source); (node?.lines ?? []).forEach(line => { if (line?.source) entries.push(line.source); }); (node?.choices ?? []).forEach(group => { if (group?.source) entries.push(group.source); (group?.options ?? []).forEach(option => { if (option?.source) entries.push(option.source); }); }); return entries; }
    function findNodeForSource(target) { if (!target) return undefined; let bestExact = undefined; let bestFallback = undefined; const targetLine = Math.max(0, (target.line ?? 0)); const targetCharacter = Math.max(0, (target.character ?? target.column ?? 0)); for (const node of graphNodes) { for (const source of collectNodeSources(node)) { const payload = sourcePayload(source); if (!payload || !sameSourcePath(payload.sourcePath, target.sourcePath)) continue; const lineDelta = Math.abs(payload.line - targetLine); const characterDelta = Math.abs(payload.character - targetCharacter); const score = lineDelta * 1000 + characterDelta; if (lineDelta === 0 && (!bestExact || score < bestExact.score)) { bestExact = { name: node.name, score }; } if (payload.line <= targetLine && (!bestFallback || (targetLine - payload.line) < bestFallback.delta || ((targetLine - payload.line) === bestFallback.delta && characterDelta < bestFallback.characterDelta))) { bestFallback = { name: node.name, delta: targetLine - payload.line, characterDelta }; } } } return bestExact?.name ?? bestFallback?.name; }
    function focusCurrentSource() { const target = document.querySelector('.source-focus'); if (target && typeof target.scrollIntoView === 'function') { target.scrollIntoView({ block: 'center', behavior: 'smooth' }); } }
    function text(value) { return document.createTextNode(value ?? ''); }
    function appendPreviewText(parent, value) { const raw = String(value ?? ''); const pattern = /\[([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*)\]/g; let cursor = 0; let match = pattern.exec(raw); while (match) { if (match.index > cursor) { parent.appendChild(text(raw.slice(cursor, match.index))); } const token = document.createElement('span'); token.className = 'query-interpolation'; token.textContent = match[0]; token.title = 'Host query interpolation'; parent.appendChild(token); cursor = match.index + match[0].length; match = pattern.exec(raw); } if (cursor < raw.length) { parent.appendChild(text(raw.slice(cursor))); } }
    function persistState() { if (vscode && typeof vscode.setState === 'function') { vscode.setState({ current, path }); } }
    function go(name) { if (!nodes.has(name)) return; current = name; path.push(name); persistState(); render(); }
    function renderSourceButton(source, label = '源码') { const payload = sourcePayload(source); if (!payload) return undefined; const button = document.createElement('button'); button.className = 'source-link'; button.textContent = label; button.title = `${payload.sourcePath}:${payload.line + 1}`; button.onclick = event => { event.stopPropagation(); openSource(payload); }; return button; }
    function currentNode() { return nodes.get(current); }
    function canContinue(node) { return !!node && (!Array.isArray(node.choices) || node.choices.length === 0) && !!node.defaultNext; }
    function continueStory() { const node = currentNode(); if (canContinue(node)) { go(node.defaultNext); } }
    function renderDiagnostics() { const el = document.getElementById('diagnostics'); clear(el); (data.diagnostics ?? []).forEach(d => { const row = document.createElement('div'); row.className = 'diagnostic'; row.textContent = `${d.severity} ${d.code} (${d.line}:${d.column}) ${d.message}`; if (d.sourcePath) { row.title = `${d.sourcePath}:${d.line}:${d.column}`; row.onclick = () => openSource({ sourcePath: d.sourcePath, line: Math.max(0, (d.line ?? 1) - 1), character: Math.max(0, (d.column ?? 1) - 1) }); row.style.cursor = 'pointer'; } el.appendChild(row); }); }
    function renderMeta(node) { const metaStrip = document.getElementById('meta-strip'); clear(metaStrip); (node.lines ?? []).filter(line => line.kind === 'Metadata' && !!line.text).forEach(line => { const pill = document.createElement('span'); pill.className = 'meta-pill'; if (sourceMatches(line.source, focusedSource)) { pill.classList.add('source-focus'); } pill.textContent = line.text; if (line.source?.sourcePath) { pill.style.cursor = 'pointer'; pill.onclick = () => openSource(sourcePayload(line.source)); } metaStrip.appendChild(pill); }); }
    function renderNodeSource(node) { const slot = document.getElementById('node-source'); clear(slot); const sourceButton = renderSourceButton(node?.source); if (sourceButton) { slot.appendChild(sourceButton); } }
    function renderStory(node) { const panel = document.getElementById('story-panel'); clear(panel); panel.classList.toggle('can-continue', canContinue(node)); panel.onclick = event => { if (event.target === panel || event.target.classList.contains('line')) { continueStory(); } }; (node.lines ?? []).filter(line => line.kind !== 'Metadata').forEach(line => { const paragraph = document.createElement('p'); paragraph.className = 'line'; if (sourceMatches(line.source, focusedSource)) { paragraph.classList.add('source-focus'); } if (line.speaker) { const speaker = document.createElement('span'); speaker.className = 'speaker'; speaker.textContent = line.speaker + '：'; paragraph.appendChild(speaker); } appendPreviewText(paragraph, line.text); panel.appendChild(paragraph); }); }
    function renderChoices(node) { const choices = document.getElementById('choices'); clear(choices); (node.choices ?? []).forEach(group => { if (group.prompt) { const prompt = document.createElement('p'); prompt.className = 'choice-prompt'; if (sourceMatches(group.source, focusedSource)) { prompt.classList.add('source-focus'); } appendPreviewText(prompt, group.prompt); choices.appendChild(prompt); } (group.options ?? []).forEach(option => { const button = document.createElement('button'); button.className = 'choice'; if (sourceMatches(option.source, focusedSource)) { button.classList.add('source-focus'); } appendPreviewText(button, option.text); button.onclick = () => go(option.target); choices.appendChild(button); }); }); }
    function renderHints(node) { const continueHint = document.getElementById('continue-hint'); const ending = document.getElementById('ending'); continueHint.textContent = canContinue(node) ? '点击正文继续' : ''; const hasChoices = Array.isArray(node?.choices) && node.choices.length > 0; ending.textContent = !hasChoices && !node?.defaultNext ? '流程到此为止。可点击 Restart 重新开始。' : ''; }
    function renderStatus(node) { document.getElementById('status').textContent = path.length > 0 ? `Step ${path.length}` : ''; document.getElementById('node-title').textContent = node?.name ?? '(empty)'; document.getElementById('back').disabled = path.length <= 1; }
    function renderRefreshStatus(state) { const refreshStatus = document.getElementById('refresh-status'); if (!refreshStatus) return; const labels = { pending: '等待刷新...', refreshing: '刷新中...' }; const label = labels[state] ?? ''; refreshStatus.textContent = label; refreshStatus.classList.toggle('is-visible', !!label); }
    function render() { const node = currentNode(); if (!node) { current = initialCurrent; path = current ? [current] : []; persistState(); const fallbackNode = currentNode(); if (!fallbackNode) { document.getElementById('node-title').textContent = '(empty)'; return; } renderStatus(fallbackNode); renderNodeSource(fallbackNode); renderMeta(fallbackNode); renderStory(fallbackNode); renderChoices(fallbackNode); renderHints(fallbackNode); focusCurrentSource(); return; } renderStatus(node); renderNodeSource(node); renderMeta(node); renderStory(node); renderChoices(node); renderHints(node); focusCurrentSource(); }
    document.getElementById('restart').onclick = () => { current = initialCurrent; path = current ? [current] : []; persistState(); render(); };
    document.getElementById('back').onclick = () => { if (path.length > 1) { path.pop(); current = path[path.length - 1]; persistState(); render(); } };
    if (vscode) { window.addEventListener('message', event => { const message = event.data || {}; if (message.type === 'previewStatus') { renderRefreshStatus(message.state); } if (message.type === 'refresh') { persistState(); renderDiagnostics(); render(); } if (message.type === 'revealSource' && message.source) { focusedSource = { sourcePath: message.source.sourcePath, line: Math.max(0, (message.source.line ?? 0)), character: Math.max(0, (message.source.character ?? message.source.column ?? 0)) }; const targetNode = findNodeForSource(focusedSource); if (targetNode && nodes.has(targetNode)) { current = targetNode; path = [targetNode]; persistState(); } render(); } }); }
    persistState(); renderDiagnostics(); render();
