using System;
using System.Collections.Generic;

namespace Inscape.Tests {

    public static partial class TestCore {

        public static int Main() {
            List<(string Name, Action Body)> tests = new List<(string Name, Action Body)> {
                ("parse graph with loop", ParseGraphWithLoop),
                ("diagnose missing target", DiagnoseMissingTarget),
                ("diagnose invalid node names", DiagnoseInvalidNodeNames),
                ("diagnose legacy node marker as content", DiagnoseLegacyNodeMarkerAsContent),
                ("parse hash title graph with Chinese jump", ParseHashTitleGraphWithChineseJump),
                ("diagnose duplicate hash titles", DiagnoseDuplicateHashTitles),
                ("warns when hash title missing leading blank line", WarnsWhenHashTitleMissingLeadingBlankLine),
                ("hashes are stable", HashesAreStable),
                ("hash ignores file path", HashIgnoresFilePath),
                ("hash ignores line movement", HashIgnoresLineMovement),
                ("hash distinguishes duplicate text", HashDistinguishesDuplicateText),
                ("anchor validator detects collisions", StoryGraphAnchorValidatorDetectsCollisions),
                ("source spans cover authoring elements", SourceSpansCoverAuthoringElements),
                ("parse choice conditions into ir", ParsesChoiceConditionsIntoIr),
                ("parse conditional jumps into ir", ParsesConditionalJumpsIntoIr),
                ("diagnose conditional jump missing fallback", DiagnosesConditionalJumpMissingFallback),
                ("diagnose unsupported condition syntax", DiagnosesUnsupportedConditionSyntax),
                ("project diagnostics preserve cross-file source", ProjectDiagnosticsPreserveCrossFileSource),
                ("language server diagnostics use editor coordinates", LanguageServerDiagnosticsUseEditorCoordinates),
                ("language server definitions use compiler source map", LanguageServerDefinitionsUseCompilerSourceMap),
                ("language server references and completions use compiler graph", LanguageServerReferencesAndCompletionsUseCompilerGraph),
                ("language server symbols and hover use compiler graph", LanguageServerSymbolsAndHoverUseCompilerGraph),
                ("language server entry probes emit stable json", LanguageServerEntryProbesEmitStableJson),
                ("language server project diagnostics apply override", LanguageServerProjectDiagnosticsApplyOverride),
                ("language server project navigation uses project graph and override", LanguageServerProjectNavigationUsesProjectGraphAndOverride),
                ("language server project completions use project graph and override", LanguageServerProjectCompletionsUseProjectGraphAndOverride),
                ("language server project hover uses project graph and override", LanguageServerProjectHoverUsesProjectGraphAndOverride),
                ("language server host schema capabilities use tooling contract", LanguageServerHostSchemaCapabilitiesUseToolingContract),
                ("language server host binding capabilities use tooling contract", LanguageServerHostBindingCapabilitiesUseToolingContract),
                ("language server stdio session serves project requests", LanguageServerStdioSessionServesProjectRequests),
                ("narrative runtime consumes compiler graph", NarrativeRuntimeConsumesCompilerGraph),
                ("narrative runtime records internal narrative facts", NarrativeRuntimeRecordsInternalNarrativeFacts),
                ("narrative runtime records displayed text log", NarrativeRuntimeRecordsDisplayedTextLog),
                ("narrative runtime log skips hidden conditional text", NarrativeRuntimeLogSkipsHiddenConditionalText),
                ("narrative runtime query provider uses delegate mock and recorded sources", NarrativeRuntimeQueryProviderUsesDelegateMockAndRecordedSources),
                ("narrative runtime condition evaluator evaluates compiler ir", NarrativeRuntimeConditionEvaluatorEvaluatesCompilerIr),
                ("narrative runtime condition evaluator uses internal facts and short circuit", NarrativeRuntimeConditionEvaluatorUsesInternalFactsAndShortCircuit),
                ("narrative runtime condition evaluator uses recorded provider values", NarrativeRuntimeConditionEvaluatorUsesRecordedProviderValues),
                ("narrative runtime condition evaluator reports runtime errors", NarrativeRuntimeConditionEvaluatorReportsRuntimeErrors),
                ("narrative runtime filters conditional choices by visible index", NarrativeRuntimeFiltersConditionalChoicesByVisibleIndex),
                ("narrative runtime follows first true conditional jump", NarrativeRuntimeFollowsFirstTrueConditionalJump),
                ("narrative runtime follows conditional fallback", NarrativeRuntimeFollowsConditionalFallback),
                ("narrative runtime reports missing conditional fallback", NarrativeRuntimeReportsMissingConditionalFallback),
                ("narrative runtime dispatches fire actions and continues", NarrativeRuntimeDispatchesFireActionsAndContinues),
                ("narrative runtime reports action dispatch errors", NarrativeRuntimeReportsActionDispatchErrors),
                ("narrative runtime waits for action resume", NarrativeRuntimeWaitsForActionResume),
                ("narrative runtime reports wait resume errors", NarrativeRuntimeReportsWaitResumeErrors),
                ("narrative runtime hands off and resumes", NarrativeRuntimeHandsOffAndResumes),
                ("narrative runtime reports handoff resume errors", NarrativeRuntimeReportsHandoffResumeErrors),
                ("narrative runtime exports and validates minimal runtime state", NarrativeRuntimeExportsAndValidatesMinimalRuntimeState),
                ("narrative runtime exports imports substate and continues", NarrativeRuntimeExportsImportsSubstateAndContinues),
                ("narrative runtime imports pending substate and resumes", NarrativeRuntimeImportsPendingSubstateAndResumes),
                ("narrative runtime rejects migratable substate without repair", NarrativeRuntimeRejectsMigratableSubstateWithoutRepair),
                ("cli runtime-project exports and validates formal runtime state", CliRuntimeProjectExportsAndValidatesFormalRuntimeState),
                ("p3 integration smoke connects usage audit conditions and runtime state", P3IntegrationSmokeConnectsUsageAuditConditionsAndRuntimeState),
                ("cli runtime-project emits runtime state", CliRuntimeProjectEmitsRuntimeState),
                ("cli runtime-project steps restored state", CliRuntimeProjectStepsRestoredState),
                ("cli runtime-project drives p4 playable runtime", CliRuntimeProjectDrivesP4PlayableRuntime),
                ("p4 integration smoke runs playable mvp sample", P4IntegrationSmokeRunsPlayableMvpSample),
                ("cli runtime-project reports p4 runtime query errors", CliRuntimeProjectReportsP4RuntimeQueryErrors),
                ("cli runtime-project reports p4 runtime action result errors", CliRuntimeProjectReportsP4RuntimeActionResultErrors),
                ("tool config resolves host bridge path", ToolConfigResolvesHostBridgePath),
                ("tool config resolves node map path", ToolConfigResolvesNodeMapPath),
                ("host schema json schema defines actions and legacy events", HostSchemaJsonSchemaDefinesActionsAndLegacyEvents),
                ("host schema action reader reports schema actions", HostSchemaActionReaderReportsSchemaActions),
                ("host schema event reader reports schema events", HostSchemaEventReaderReportsSchemaEvents),
                ("query interpolation audit reports host schema hints", QueryInterpolationAuditReportsHostSchemaHints),
                ("usage manifest reports queries actions and required ids", UsageManifestReportsQueriesActionsAndRequiredIds),
                ("host integration audit reports schema and bridge gaps", HostIntegrationAuditReportsSchemaAndBridgeGaps),
                ("host integration package manifest uses package relative paths", HostIntegrationPackageManifestUsesPackageRelativePaths),
                ("host integration package path guard rejects unsafe paths", HostIntegrationPackagePathGuardRejectsUnsafePaths),
                ("host integration package readiness report reads ready package", HostIntegrationPackageReadinessReportReadsReadyPackage),
                ("host integration package readiness report detects missing required artifact", HostIntegrationPackageReadinessReportDetectsMissingRequiredArtifact),
                ("host integration package readiness report detects invalid json artifact", HostIntegrationPackageReadinessReportDetectsInvalidJsonArtifact),
                ("host integration package readiness report aggregates diagnostics", HostIntegrationPackageReadinessReportAggregatesDiagnostics),
                ("host integration package readiness report summarizes existing candidate", HostIntegrationPackageReadinessReportSummarizesExistingCandidate),
                ("host bridge candidate generation reports empty package", HostBridgeCandidateGenerationReportsEmptyPackage),
                ("host bridge candidate generation reports ready candidates", HostBridgeCandidateGenerationReportsReadyCandidates),
                ("host bridge candidate generation blocks unknown schema capabilities", HostBridgeCandidateGenerationBlocksUnknownSchemaCapabilities),
                ("host bridge candidate generation reports invalid artifact", HostBridgeCandidateGenerationReportsInvalidArtifact),
                ("host bridge candidate generation reports incompatible artifact", HostBridgeCandidateGenerationReportsIncompatibleArtifact),
                ("host bridge candidate generation ignores invalid optional readiness report", HostBridgeCandidateGenerationIgnoresInvalidOptionalReadinessReport),
                ("story node map update preserves ids and marks missing nodes", StoryNodeMapUpdatePreservesIdsAndMarksMissingNodes),
                ("story node map update detects unambiguous renames", StoryNodeMapUpdateDetectsUnambiguousRenames),
                ("story node map update skips ambiguous rename matches", StoryNodeMapUpdateSkipsAmbiguousRenameMatches),
                ("story node map update marks duplicate ids as conflict", StoryNodeMapUpdateMarksDuplicateIdsAsConflict),
                ("story node map update report includes renamed items", StoryNodeMapUpdateReportIncludesRenamedItems),
                ("story node map update report includes manual review candidates", StoryNodeMapUpdateReportIncludesManualReviewCandidates),
                ("story node map review action applies candidate stable id", StoryNodeMapReviewActionAppliesCandidateStableId),
                ("story node map review action rejects missing entries", StoryNodeMapReviewActionRejectsMissingEntries),
                ("cli diagnose emits json", CliDiagnoseEmitsJson),
                ("cli commands lists command reference", CliCommandsListsCommandReference),
                ("cli help emits command details", CliHelpEmitsCommandDetails),
                ("cli help emits host integration package details", CliHelpEmitsHostIntegrationPackageDetails),
                ("cli help emits host integration readiness report details", CliHelpEmitsHostIntegrationReadinessReportDetails),
                ("cli help emits host bridge candidate details", CliHelpEmitsHostBridgeCandidateDetails),
                ("cli audit-query-interpolation-project emits json", CliAuditQueryInterpolationProjectEmitsJson),
                ("cli inspect-host-schema-project emits json", CliInspectHostSchemaProjectEmitsJson),
                ("cli inspect-usage-project emits json", CliInspectUsageProjectEmitsJson),
                ("cli audit-host-integration-project emits json", CliAuditHostIntegrationProjectEmitsJson),
                ("cli host integration package writes manifest", CliHostIntegrationPackageWritesManifest),
                ("cli host bridge candidate package writes candidate", CliHostBridgeCandidatePackageWritesCandidate),
                ("cli update-node-map-project writes stable node map", CliUpdateNodeMapProjectWritesStableNodeMap),
                ("cli update-node-map-project writes review report", CliUpdateNodeMapProjectWritesReviewReport),
                ("cli apply-node-map-candidate-project writes shared review decision", CliApplyNodeMapCandidateProjectWritesSharedReviewDecision),
                ("cli export-host-schema-template emits json", CliExportHostSchemaTemplateEmitsJson),
                ("project compiler resolves cross-file targets", StoryGraphCompilerDomainResolvesCrossFileTargets),
                ("project compiler diagnoses duplicate nodes", StoryGraphCompilerDomainDiagnosesDuplicateNodes),
                ("project compiler diagnoses duplicate hash titles", StoryGraphCompilerDomainDiagnosesDuplicateHashTitles),
                ("cli diagnose-project applies override", CliDiagnoseProjectAppliesOverride),
                ("cli compile-project emits project ir", CliCompileProjectEmitsProjectIr),
                ("project compiler uses entry metadata", StoryGraphCompilerDomainUsesEntryMetadata),
                ("project compiler applies entry override", StoryGraphCompilerDomainAppliesEntryOverride),
                ("project compiler diagnoses missing entry override", StoryGraphCompilerDomainDiagnosesMissingEntryOverride),
                ("project compiler diagnoses multiple entries", StoryGraphCompilerDomainDiagnosesMultipleEntries),
                ("project compiler reports fallback entry", StoryGraphCompilerDomainReportsFallbackEntry),
                ("cli preview-project emits html", CliPreviewProjectEmitsHtml),
                ("cli preview-project applies entry override", CliPreviewProjectAppliesEntryOverride),
                ("preview html converts compiler source coordinates", PreviewHtmlConvertsCompilerSourceCoordinates),
                ("preview html styles query interpolation tokens", PreviewHtmlStylesQueryInterpolationTokens),
                ("preview html provider adds csp to fallback pages", PreviewHtmlProviderAddsCspToFallbackPages),
                ("preview source controller keeps column fallback", PreviewSourceControllerKeepsColumnFallback),
                ("preview reveal bridge trims choice prefixes from link range", PreviewRevealBridgeTrimsChoicePrefixesFromLinkRange),
                ("cli extract-l10n emits csv", CliExtractL10nEmitsCsv),
                ("cli extract-l10n-project emits csv", CliExtractL10nProjectEmitsCsv),
                ("cli update-l10n preserves translations", CliUpdateL10nPreservesTranslations),
                ("cli update-l10n-project preserves translations", CliUpdateL10nProjectPreservesTranslations),
                ("cli update-l10n-project applies translation overrides", CliUpdateL10nProjectAppliesTranslationOverrides),
                ("cli update-l10n-project rejects non localization csv", CliUpdateL10nProjectRejectsNonLocalizationCsv),
                ("localization alignment audit reports review statuses", LocalizationAlignmentAuditReportsReviewStatuses),
                ("localization review presenter summarizes additional candidates", LocalizationReviewPresenterSummarizesAdditionalCandidates),
                ("localization alignment audit keeps low confidence similar text as conflict", LocalizationAlignmentAuditKeepsLowConfidenceSimilarTextAsConflict),
                ("localization alignment audit prefers near sequence when similarity ties", LocalizationAlignmentAuditPrefersNearSequenceWhenSimilarityTies),
                ("localization alignment audit prefers near context shape when sequence ties", LocalizationAlignmentAuditPrefersNearContextShapeWhenSequenceTies),
                ("localization alignment audit prefers keyword fingerprint when context is close", LocalizationAlignmentAuditPrefersKeywordFingerprintWhenContextIsClose),
                ("localization alignment audit prefers neighbor shape when fingerprint is close", LocalizationAlignmentAuditPrefersNeighborShapeWhenFingerprintIsClose),
                ("localization alignment audit prefers matching local context", LocalizationAlignmentAuditPrefersMatchingLocalContext),
                ("localization alignment audit records near local context", LocalizationAlignmentAuditRecordsNearLocalContext),
                ("localization alignment audit uses line sidecar identity", LocalizationAlignmentAuditUsesLineSidecarIdentity),
                ("localization alignment audit resolves close candidates by line identity", LocalizationAlignmentAuditResolvesCloseCandidatesByLineIdentity),
                ("localization alignment audit keeps rewritten same line candidate", LocalizationAlignmentAuditKeepsRewrittenSameLineCandidate),
                ("localization alignment audit ranks exact line identity before text similarity", LocalizationAlignmentAuditRanksExactLineIdentityBeforeTextSimilarity),
                ("cli audit-l10n-alignment-project emits json", CliAuditL10nAlignmentProjectEmitsJson),
                ("cli audit-l10n-alignment-project emits text", CliAuditL10nAlignmentProjectEmitsText),
                ("cli audit-l10n-alignment-project reports line identity status", CliAuditL10nAlignmentProjectReportsLineIdentityStatus),
                ("cli audit-l10n-alignment-project reports line identity drift", CliAuditL10nAlignmentProjectReportsLineIdentityDrift),
                ("cli refresh localization line state emits refresh result json", CliRefreshLocalizationLineStateEmitsRefreshResultJson),
                ("localization line map refresh tracks changed added and removed lines", LocalizationLineMapRefreshTracksChangedAddedAndRemovedLines),
                ("tool config resolves localization line map path", ToolConfigResolvesLocalizationLineMapPath),
                ("localization line map writer creates backup and restores it", LocalizationLineMapWriterCreatesBackupAndRestoresIt),
                ("localization line map refresh stores source fingerprint", LocalizationLineMapRefreshStoresSourceFingerprint),
                ("localization line map refresh reports drift when fingerprint changed", LocalizationLineMapRefreshReportsDriftWhenFingerprintChanged),
                ("localization line map refresh treats inserted middle line as added", LocalizationLineMapRefreshTreatsInsertedMiddleLineAsAdded),
                ("localization line map refresh treats deleted middle line as removed", LocalizationLineMapRefreshTreatsDeletedMiddleLineAsRemoved),
                ("localization line map refresh keeps first line id when splitting line", LocalizationLineMapRefreshKeepsFirstLineIdWhenSplittingLine),
                ("localization line map refresh keeps first line id when merging lines", LocalizationLineMapRefreshKeepsFirstLineIdWhenMergingLines),
                ("localization line map refresh keeps stable ids for duplicate neighbor lines", LocalizationLineMapRefreshKeepsStableIdsForDuplicateNeighborLines),
                ("localization line map refresh treats complex replacement as add and remove", LocalizationLineMapRefreshTreatsComplexReplacementAsAddAndRemove),
                ("vscode localization command exposes review alignment entry", VSCodeLocalizationCommandExposesReviewAlignmentEntry),
            };

            int failed = 0;
            foreach ((string name, Action body) in tests) {
                try {
                    body();
                    Console.WriteLine("[pass] " + name);
                } catch (Exception ex) {
                    failed += 1;
                    Console.Error.WriteLine("[fail] " + name + ": " + ex.Message);
                }
            }

            return failed == 0 ? 0 : 1;
        }
    }
}
